<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: CanalProtocol.proto

namespace Com\Alibaba\Otter\Canal\Protocol;

use UnexpectedValueException;

/**
 * Protobuf type <code>com.alibaba.otter.canal.protocol.Compression</code>
 */
class Compression
{
    /**
     * Generated from protobuf enum <code>COMPRESSIONCOMPATIBLEPROTO2 = 0;</code>
     */
    const COMPRESSIONCOMPATIBLEPROTO2 = 0;
    /**
     * Generated from protobuf enum <code>NONE = 1;</code>
     */
    const NONE = 1;
    /**
     * Generated from protobuf enum <code>ZLIB = 2;</code>
     */
    const ZLIB = 2;
    /**
     * Generated from protobuf enum <code>GZIP = 3;</code>
     */
    const GZIP = 3;
    /**
     * Generated from protobuf enum <code>LZF = 4;</code>
     */
    const LZF = 4;

    private static $valueToName = [
        self::COMPRESSIONCOMPATIBLEPROTO2 => 'COMPRESSIONCOMPATIBLEPROTO2',
        self::NONE => 'NONE',
        self::ZLIB => 'ZLIB',
        self::GZIP => 'GZIP',
        self::LZF => 'LZF',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

