<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: EntryProtocol.proto

namespace Com\Alibaba\Otter\Canal\Protocol;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 ****************************************************************
 * message model
 *如果要在Enum中新增类型，确保以前的类型的下标值不变.
 ***************************************************************
 *
 * Generated from protobuf message <code>com.alibaba.otter.canal.protocol.Entry</code>
 */
final class Entry extends \Google\Protobuf\Internal\Message
{
    /**
     **协议头部信息*
     *
     * Generated from protobuf field <code>.com.alibaba.otter.canal.protocol.Header header = 1;</code>
     */
    private $header = null;
    /**
     **传输的二进制数组*
     *
     * Generated from protobuf field <code>bytes storeValue = 3;</code>
     */
    private $storeValue = '';
    protected $entryType_present;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Com\Alibaba\Otter\Canal\Protocol\Header $header
     *          *协议头部信息*
     *     @type int $entryType
     *     @type string $storeValue
     *          *传输的二进制数组*
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\EntryProtocol::initOnce();
        parent::__construct($data);
    }

    /**
     **协议头部信息*
     *
     * Generated from protobuf field <code>.com.alibaba.otter.canal.protocol.Header header = 1;</code>
     * @return \Com\Alibaba\Otter\Canal\Protocol\Header
     */
    public function getHeader()
    {
        return $this->header;
    }

    /**
     **协议头部信息*
     *
     * Generated from protobuf field <code>.com.alibaba.otter.canal.protocol.Header header = 1;</code>
     * @param \Com\Alibaba\Otter\Canal\Protocol\Header $var
     * @return $this
     */
    public function setHeader($var)
    {
        GPBUtil::checkMessage($var, \Com\Alibaba\Otter\Canal\Protocol\Header::class);
        $this->header = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.com.alibaba.otter.canal.protocol.EntryType entryType = 2;</code>
     * @return int
     */
    public function getEntryType()
    {
        return $this->readOneof(2);
    }

    /**
     * Generated from protobuf field <code>.com.alibaba.otter.canal.protocol.EntryType entryType = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setEntryType($var)
    {
        GPBUtil::checkEnum($var, \Com\Alibaba\Otter\Canal\Protocol\EntryType::class);
        $this->writeOneof(2, $var);

        return $this;
    }

    /**
     **传输的二进制数组*
     *
     * Generated from protobuf field <code>bytes storeValue = 3;</code>
     * @return string
     */
    public function getStoreValue()
    {
        return $this->storeValue;
    }

    /**
     **传输的二进制数组*
     *
     * Generated from protobuf field <code>bytes storeValue = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setStoreValue($var)
    {
        GPBUtil::checkString($var, False);
        $this->storeValue = $var;

        return $this;
    }

    /**
     * @return string
     */
    public function getEntryTypePresent()
    {
        return $this->whichOneof("entryType_present");
    }

}

