<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: EntryProtocol.proto

namespace Com\Alibaba\Otter\Canal\Protocol;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 **message Header*
 *
 * Generated from protobuf message <code>com.alibaba.otter.canal.protocol.Header</code>
 */
final class Header extends \Google\Protobuf\Internal\Message
{
    /**
     **binlog/redolog 文件名*
     *
     * Generated from protobuf field <code>string logfileName = 2;</code>
     */
    private $logfileName = '';
    /**
     **binlog/redolog 文件的偏移位置*
     *
     * Generated from protobuf field <code>int64 logfileOffset = 3;</code>
     */
    private $logfileOffset = 0;
    /**
     **服务端serverId*
     *
     * Generated from protobuf field <code>int64 serverId = 4;</code>
     */
    private $serverId = 0;
    /**
     ** 变更数据的编码 *
     *
     * Generated from protobuf field <code>string serverenCode = 5;</code>
     */
    private $serverenCode = '';
    /**
     **变更数据的执行时间 *
     *
     * Generated from protobuf field <code>int64 executeTime = 6;</code>
     */
    private $executeTime = 0;
    /**
     ** 变更数据的schemaname*
     *
     * Generated from protobuf field <code>string schemaName = 8;</code>
     */
    private $schemaName = '';
    /**
     **变更数据的tablename*
     *
     * Generated from protobuf field <code>string tableName = 9;</code>
     */
    private $tableName = '';
    /**
     **每个event的长度*
     *
     * Generated from protobuf field <code>int64 eventLength = 10;</code>
     */
    private $eventLength = 0;
    /**
     **预留扩展*
     *
     * Generated from protobuf field <code>repeated .com.alibaba.otter.canal.protocol.Pair props = 12;</code>
     */
    private $props;
    /**
     **当前事务的gitd*
     *
     * Generated from protobuf field <code>string gtid = 13;</code>
     */
    private $gtid = '';
    protected $version_present;
    protected $sourceType_present;
    protected $eventType_present;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $version
     *     @type string $logfileName
     *          *binlog/redolog 文件名*
     *     @type int|string $logfileOffset
     *          *binlog/redolog 文件的偏移位置*
     *     @type int|string $serverId
     *          *服务端serverId*
     *     @type string $serverenCode
     *          * 变更数据的编码 *
     *     @type int|string $executeTime
     *          *变更数据的执行时间 *
     *     @type int $sourceType
     *     @type string $schemaName
     *          * 变更数据的schemaname*
     *     @type string $tableName
     *          *变更数据的tablename*
     *     @type int|string $eventLength
     *          *每个event的长度*
     *     @type int $eventType
     *     @type \Com\Alibaba\Otter\Canal\Protocol\Pair[]|\Google\Protobuf\Internal\RepeatedField $props
     *          *预留扩展*
     *     @type string $gtid
     *          *当前事务的gitd*
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\EntryProtocol::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int32 version = 1;</code>
     * @return int
     */
    public function getVersion()
    {
        return $this->readOneof(1);
    }

    /**
     * Generated from protobuf field <code>int32 version = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setVersion($var)
    {
        GPBUtil::checkInt32($var);
        $this->writeOneof(1, $var);

        return $this;
    }

    /**
     **binlog/redolog 文件名*
     *
     * Generated from protobuf field <code>string logfileName = 2;</code>
     * @return string
     */
    public function getLogfileName()
    {
        return $this->logfileName;
    }

    /**
     **binlog/redolog 文件名*
     *
     * Generated from protobuf field <code>string logfileName = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setLogfileName($var)
    {
        GPBUtil::checkString($var, True);
        $this->logfileName = $var;

        return $this;
    }

    /**
     **binlog/redolog 文件的偏移位置*
     *
     * Generated from protobuf field <code>int64 logfileOffset = 3;</code>
     * @return int|string
     */
    public function getLogfileOffset()
    {
        return $this->logfileOffset;
    }

    /**
     **binlog/redolog 文件的偏移位置*
     *
     * Generated from protobuf field <code>int64 logfileOffset = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setLogfileOffset($var)
    {
        GPBUtil::checkInt64($var);
        $this->logfileOffset = $var;

        return $this;
    }

    /**
     **服务端serverId*
     *
     * Generated from protobuf field <code>int64 serverId = 4;</code>
     * @return int|string
     */
    public function getServerId()
    {
        return $this->serverId;
    }

    /**
     **服务端serverId*
     *
     * Generated from protobuf field <code>int64 serverId = 4;</code>
     * @param int|string $var
     * @return $this
     */
    public function setServerId($var)
    {
        GPBUtil::checkInt64($var);
        $this->serverId = $var;

        return $this;
    }

    /**
     ** 变更数据的编码 *
     *
     * Generated from protobuf field <code>string serverenCode = 5;</code>
     * @return string
     */
    public function getServerenCode()
    {
        return $this->serverenCode;
    }

    /**
     ** 变更数据的编码 *
     *
     * Generated from protobuf field <code>string serverenCode = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setServerenCode($var)
    {
        GPBUtil::checkString($var, True);
        $this->serverenCode = $var;

        return $this;
    }

    /**
     **变更数据的执行时间 *
     *
     * Generated from protobuf field <code>int64 executeTime = 6;</code>
     * @return int|string
     */
    public function getExecuteTime()
    {
        return $this->executeTime;
    }

    /**
     **变更数据的执行时间 *
     *
     * Generated from protobuf field <code>int64 executeTime = 6;</code>
     * @param int|string $var
     * @return $this
     */
    public function setExecuteTime($var)
    {
        GPBUtil::checkInt64($var);
        $this->executeTime = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.com.alibaba.otter.canal.protocol.Type sourceType = 7;</code>
     * @return int
     */
    public function getSourceType()
    {
        return $this->readOneof(7);
    }

    /**
     * Generated from protobuf field <code>.com.alibaba.otter.canal.protocol.Type sourceType = 7;</code>
     * @param int $var
     * @return $this
     */
    public function setSourceType($var)
    {
        GPBUtil::checkEnum($var, \Com\Alibaba\Otter\Canal\Protocol\Type::class);
        $this->writeOneof(7, $var);

        return $this;
    }

    /**
     ** 变更数据的schemaname*
     *
     * Generated from protobuf field <code>string schemaName = 8;</code>
     * @return string
     */
    public function getSchemaName()
    {
        return $this->schemaName;
    }

    /**
     ** 变更数据的schemaname*
     *
     * Generated from protobuf field <code>string schemaName = 8;</code>
     * @param string $var
     * @return $this
     */
    public function setSchemaName($var)
    {
        GPBUtil::checkString($var, True);
        $this->schemaName = $var;

        return $this;
    }

    /**
     **变更数据的tablename*
     *
     * Generated from protobuf field <code>string tableName = 9;</code>
     * @return string
     */
    public function getTableName()
    {
        return $this->tableName;
    }

    /**
     **变更数据的tablename*
     *
     * Generated from protobuf field <code>string tableName = 9;</code>
     * @param string $var
     * @return $this
     */
    public function setTableName($var)
    {
        GPBUtil::checkString($var, True);
        $this->tableName = $var;

        return $this;
    }

    /**
     **每个event的长度*
     *
     * Generated from protobuf field <code>int64 eventLength = 10;</code>
     * @return int|string
     */
    public function getEventLength()
    {
        return $this->eventLength;
    }

    /**
     **每个event的长度*
     *
     * Generated from protobuf field <code>int64 eventLength = 10;</code>
     * @param int|string $var
     * @return $this
     */
    public function setEventLength($var)
    {
        GPBUtil::checkInt64($var);
        $this->eventLength = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.com.alibaba.otter.canal.protocol.EventType eventType = 11;</code>
     * @return int
     */
    public function getEventType()
    {
        return $this->readOneof(11);
    }

    /**
     * Generated from protobuf field <code>.com.alibaba.otter.canal.protocol.EventType eventType = 11;</code>
     * @param int $var
     * @return $this
     */
    public function setEventType($var)
    {
        GPBUtil::checkEnum($var, \Com\Alibaba\Otter\Canal\Protocol\EventType::class);
        $this->writeOneof(11, $var);

        return $this;
    }

    /**
     **预留扩展*
     *
     * Generated from protobuf field <code>repeated .com.alibaba.otter.canal.protocol.Pair props = 12;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getProps()
    {
        return $this->props;
    }

    /**
     **预留扩展*
     *
     * Generated from protobuf field <code>repeated .com.alibaba.otter.canal.protocol.Pair props = 12;</code>
     * @param \Com\Alibaba\Otter\Canal\Protocol\Pair[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setProps($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Com\Alibaba\Otter\Canal\Protocol\Pair::class);
        $this->props = $arr;

        return $this;
    }

    /**
     **当前事务的gitd*
     *
     * Generated from protobuf field <code>string gtid = 13;</code>
     * @return string
     */
    public function getGtid()
    {
        return $this->gtid;
    }

    /**
     **当前事务的gitd*
     *
     * Generated from protobuf field <code>string gtid = 13;</code>
     * @param string $var
     * @return $this
     */
    public function setGtid($var)
    {
        GPBUtil::checkString($var, True);
        $this->gtid = $var;

        return $this;
    }

    /**
     * @return string
     */
    public function getVersionPresent()
    {
        return $this->whichOneof("version_present");
    }

    /**
     * @return string
     */
    public function getSourceTypePresent()
    {
        return $this->whichOneof("sourceType_present");
    }

    /**
     * @return string
     */
    public function getEventTypePresent()
    {
        return $this->whichOneof("eventType_present");
    }

}

