<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: EntryProtocol.proto

namespace Com\Alibaba\Otter\Canal\Protocol;

use UnexpectedValueException;

/**
 **数据库类型*
 *
 * Protobuf type <code>com.alibaba.otter.canal.protocol.Type</code>
 */
class Type
{
    /**
     * Generated from protobuf enum <code>TYPECOMPATIBLEPROTO2 = 0;</code>
     */
    const TYPECOMPATIBLEPROTO2 = 0;
    /**
     * Generated from protobuf enum <code>ORACLE = 1;</code>
     */
    const ORACLE = 1;
    /**
     * Generated from protobuf enum <code>MYSQL = 2;</code>
     */
    const MYSQL = 2;
    /**
     * Generated from protobuf enum <code>PGSQL = 3;</code>
     */
    const PGSQL = 3;

    private static $valueToName = [
        self::TYPECOMPATIBLEPROTO2 => 'TYPECOMPATIBLEPROTO2',
        self::ORACLE => 'ORACLE',
        self::MYSQL => 'MYSQL',
        self::PGSQL => 'PGSQL',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

