<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: CanalProtocol.proto

namespace Com\Alibaba\Otter\Canal\Protocol;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * client authentication
 *
 * Generated from protobuf message <code>com.alibaba.otter.canal.protocol.ClientAuth</code>
 */
final class ClientAuth extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string username = 1;</code>
     */
    private $username = '';
    /**
     * hashed password with seeds from Handshake message
     *
     * Generated from protobuf field <code>bytes password = 2;</code>
     */
    private $password = '';
    /**
     * Generated from protobuf field <code>string destination = 5;</code>
     */
    private $destination = '';
    /**
     * Generated from protobuf field <code>string client_id = 6;</code>
     */
    private $client_id = '';
    /**
     * Generated from protobuf field <code>string filter = 7;</code>
     */
    private $filter = '';
    /**
     * Generated from protobuf field <code>int64 start_timestamp = 8;</code>
     */
    private $start_timestamp = 0;
    protected $net_read_timeout_present;
    protected $net_write_timeout_present;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $username
     *     @type string $password
     *           hashed password with seeds from Handshake message
     *     @type int $net_read_timeout
     *           in seconds
     *     @type int $net_write_timeout
     *           in seconds
     *     @type string $destination
     *     @type string $client_id
     *     @type string $filter
     *     @type int|string $start_timestamp
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\CanalProtocol::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string username = 1;</code>
     * @return string
     */
    public function getUsername()
    {
        return $this->username;
    }

    /**
     * Generated from protobuf field <code>string username = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setUsername($var)
    {
        GPBUtil::checkString($var, True);
        $this->username = $var;

        return $this;
    }

    /**
     * hashed password with seeds from Handshake message
     *
     * Generated from protobuf field <code>bytes password = 2;</code>
     * @return string
     */
    public function getPassword()
    {
        return $this->password;
    }

    /**
     * hashed password with seeds from Handshake message
     *
     * Generated from protobuf field <code>bytes password = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setPassword($var)
    {
        GPBUtil::checkString($var, False);
        $this->password = $var;

        return $this;
    }

    /**
     * in seconds
     *
     * Generated from protobuf field <code>int32 net_read_timeout = 3;</code>
     * @return int
     */
    public function getNetReadTimeout()
    {
        return $this->readOneof(3);
    }

    /**
     * in seconds
     *
     * Generated from protobuf field <code>int32 net_read_timeout = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setNetReadTimeout($var)
    {
        GPBUtil::checkInt32($var);
        $this->writeOneof(3, $var);

        return $this;
    }

    /**
     * in seconds
     *
     * Generated from protobuf field <code>int32 net_write_timeout = 4;</code>
     * @return int
     */
    public function getNetWriteTimeout()
    {
        return $this->readOneof(4);
    }

    /**
     * in seconds
     *
     * Generated from protobuf field <code>int32 net_write_timeout = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setNetWriteTimeout($var)
    {
        GPBUtil::checkInt32($var);
        $this->writeOneof(4, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>string destination = 5;</code>
     * @return string
     */
    public function getDestination()
    {
        return $this->destination;
    }

    /**
     * Generated from protobuf field <code>string destination = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setDestination($var)
    {
        GPBUtil::checkString($var, True);
        $this->destination = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string client_id = 6;</code>
     * @return string
     */
    public function getClientId()
    {
        return $this->client_id;
    }

    /**
     * Generated from protobuf field <code>string client_id = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setClientId($var)
    {
        GPBUtil::checkString($var, True);
        $this->client_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string filter = 7;</code>
     * @return string
     */
    public function getFilter()
    {
        return $this->filter;
    }

    /**
     * Generated from protobuf field <code>string filter = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setFilter($var)
    {
        GPBUtil::checkString($var, True);
        $this->filter = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 start_timestamp = 8;</code>
     * @return int|string
     */
    public function getStartTimestamp()
    {
        return $this->start_timestamp;
    }

    /**
     * Generated from protobuf field <code>int64 start_timestamp = 8;</code>
     * @param int|string $var
     * @return $this
     */
    public function setStartTimestamp($var)
    {
        GPBUtil::checkInt64($var);
        $this->start_timestamp = $var;

        return $this;
    }

    /**
     * @return string
     */
    public function getNetReadTimeoutPresent()
    {
        return $this->whichOneof("net_read_timeout_present");
    }

    /**
     * @return string
     */
    public function getNetWriteTimeoutPresent()
    {
        return $this->whichOneof("net_write_timeout_present");
    }

}

