<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: CanalProtocol.proto

namespace Com\Alibaba\Otter\Canal\Protocol;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * TBD when new packets are required
 *
 * Generated from protobuf message <code>com.alibaba.otter.canal.protocol.Dump</code>
 */
final class Dump extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string journal = 1;</code>
     */
    private $journal = '';
    /**
     * Generated from protobuf field <code>int64 position = 2;</code>
     */
    private $position = 0;
    protected $timestamp_present;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $journal
     *     @type int|string $position
     *     @type int|string $timestamp
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\CanalProtocol::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string journal = 1;</code>
     * @return string
     */
    public function getJournal()
    {
        return $this->journal;
    }

    /**
     * Generated from protobuf field <code>string journal = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setJournal($var)
    {
        GPBUtil::checkString($var, True);
        $this->journal = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 position = 2;</code>
     * @return int|string
     */
    public function getPosition()
    {
        return $this->position;
    }

    /**
     * Generated from protobuf field <code>int64 position = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setPosition($var)
    {
        GPBUtil::checkInt64($var);
        $this->position = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 timestamp = 3;</code>
     * @return int|string
     */
    public function getTimestamp()
    {
        return $this->readOneof(3);
    }

    /**
     * Generated from protobuf field <code>int64 timestamp = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setTimestamp($var)
    {
        GPBUtil::checkInt64($var);
        $this->writeOneof(3, $var);

        return $this;
    }

    /**
     * @return string
     */
    public function getTimestampPresent()
    {
        return $this->whichOneof("timestamp_present");
    }

}

