<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: CanalProtocol.proto

namespace Com\Alibaba\Otter\Canal\Protocol;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>com.alibaba.otter.canal.protocol.Handshake</code>
 */
final class Handshake extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bytes seeds = 2;</code>
     */
    private $seeds = '';
    /**
     * Generated from protobuf field <code>.com.alibaba.otter.canal.protocol.Compression supported_compressions = 3;</code>
     */
    private $supported_compressions = 0;
    protected $communication_encoding_present;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $communication_encoding
     *     @type string $seeds
     *     @type int $supported_compressions
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\CanalProtocol::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string communication_encoding = 1;</code>
     * @return string
     */
    public function getCommunicationEncoding()
    {
        return $this->readOneof(1);
    }

    /**
     * Generated from protobuf field <code>string communication_encoding = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setCommunicationEncoding($var)
    {
        GPBUtil::checkString($var, True);
        $this->writeOneof(1, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes seeds = 2;</code>
     * @return string
     */
    public function getSeeds()
    {
        return $this->seeds;
    }

    /**
     * Generated from protobuf field <code>bytes seeds = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setSeeds($var)
    {
        GPBUtil::checkString($var, False);
        $this->seeds = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.com.alibaba.otter.canal.protocol.Compression supported_compressions = 3;</code>
     * @return int
     */
    public function getSupportedCompressions()
    {
        return $this->supported_compressions;
    }

    /**
     * Generated from protobuf field <code>.com.alibaba.otter.canal.protocol.Compression supported_compressions = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setSupportedCompressions($var)
    {
        GPBUtil::checkEnum($var, \Com\Alibaba\Otter\Canal\Protocol\Compression::class);
        $this->supported_compressions = $var;

        return $this;
    }

    /**
     * @return string
     */
    public function getCommunicationEncodingPresent()
    {
        return $this->whichOneof("communication_encoding_present");
    }

}

