<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: CanalProtocol.proto

namespace Com\Alibaba\Otter\Canal\Protocol;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>com.alibaba.otter.canal.protocol.HeartBeat</code>
 */
final class HeartBeat extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int64 send_timestamp = 1;</code>
     */
    private $send_timestamp = 0;
    /**
     * Generated from protobuf field <code>int64 start_timestamp = 2;</code>
     */
    private $start_timestamp = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $send_timestamp
     *     @type int|string $start_timestamp
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\CanalProtocol::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int64 send_timestamp = 1;</code>
     * @return int|string
     */
    public function getSendTimestamp()
    {
        return $this->send_timestamp;
    }

    /**
     * Generated from protobuf field <code>int64 send_timestamp = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setSendTimestamp($var)
    {
        GPBUtil::checkInt64($var);
        $this->send_timestamp = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 start_timestamp = 2;</code>
     * @return int|string
     */
    public function getStartTimestamp()
    {
        return $this->start_timestamp;
    }

    /**
     * Generated from protobuf field <code>int64 start_timestamp = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setStartTimestamp($var)
    {
        GPBUtil::checkInt64($var);
        $this->start_timestamp = $var;

        return $this;
    }

}

