<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: CanalProtocol.proto

namespace Com\Alibaba\Otter\Canal\Protocol;

use UnexpectedValueException;

/**
 * Protobuf type <code>com.alibaba.otter.canal.protocol.PacketType</code>
 */
class PacketType
{
    /**
     *compatible
     *
     * Generated from protobuf enum <code>PACKAGETYPECOMPATIBLEPROTO2 = 0;</code>
     */
    const PACKAGETYPECOMPATIBLEPROTO2 = 0;
    /**
     * Generated from protobuf enum <code>HANDSHAKE = 1;</code>
     */
    const HANDSHAKE = 1;
    /**
     * Generated from protobuf enum <code>CLIENTAUTHENTICATION = 2;</code>
     */
    const CLIENTAUTHENTICATION = 2;
    /**
     * Generated from protobuf enum <code>ACK = 3;</code>
     */
    const ACK = 3;
    /**
     * Generated from protobuf enum <code>SUBSCRIPTION = 4;</code>
     */
    const SUBSCRIPTION = 4;
    /**
     * Generated from protobuf enum <code>UNSUBSCRIPTION = 5;</code>
     */
    const UNSUBSCRIPTION = 5;
    /**
     * Generated from protobuf enum <code>GET = 6;</code>
     */
    const GET = 6;
    /**
     * Generated from protobuf enum <code>MESSAGES = 7;</code>
     */
    const MESSAGES = 7;
    /**
     * Generated from protobuf enum <code>CLIENTACK = 8;</code>
     */
    const CLIENTACK = 8;
    /**
     * management part
     *
     * Generated from protobuf enum <code>SHUTDOWN = 9;</code>
     */
    const SHUTDOWN = 9;
    /**
     * integration
     *
     * Generated from protobuf enum <code>DUMP = 10;</code>
     */
    const DUMP = 10;
    /**
     * Generated from protobuf enum <code>HEARTBEAT = 11;</code>
     */
    const HEARTBEAT = 11;
    /**
     * Generated from protobuf enum <code>CLIENTROLLBACK = 12;</code>
     */
    const CLIENTROLLBACK = 12;

    private static $valueToName = [
        self::PACKAGETYPECOMPATIBLEPROTO2 => 'PACKAGETYPECOMPATIBLEPROTO2',
        self::HANDSHAKE => 'HANDSHAKE',
        self::CLIENTAUTHENTICATION => 'CLIENTAUTHENTICATION',
        self::ACK => 'ACK',
        self::SUBSCRIPTION => 'SUBSCRIPTION',
        self::UNSUBSCRIPTION => 'UNSUBSCRIPTION',
        self::GET => 'GET',
        self::MESSAGES => 'MESSAGES',
        self::CLIENTACK => 'CLIENTACK',
        self::SHUTDOWN => 'SHUTDOWN',
        self::DUMP => 'DUMP',
        self::HEARTBEAT => 'HEARTBEAT',
        self::CLIENTROLLBACK => 'CLIENTROLLBACK',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

